### ISSUE TITLE
Demo Error

### ISSUE THREAD

**Issue by Xu-Zirui** [naver/mast3r#12]
Hello，Thanks for your work. When i use demo, some error happen, like this:

- adding /tmp/gradio/08c3bff2b2bce0a6c9a15cf084d147587905aabe/微信图片_20240716153639.jpg with resolution 4032x3024 --> 512x384
 - adding /tmp/gradio/1a5abcb9115eccd5905c71f9cefdd19a4e741bf3/微信图片_20240716153648.jpg with resolution 4032x3024 --> 512x384
 - adding /tmp/gradio/ca2f77d2af830164cea68f54e110848a5914eec9/微信图片_20240716153653.jpg with resolution 4032x3024 --> 512x384
 - adding /tmp/gradio/7b640801a8f9a48d0c618aef66335f9e72f41d85/微信图片_20240716153700.jpg with resolution 4032x3024 --> 512x384
 - adding /tmp/gradio/f51fce5d8ee05119fb005cc3fdc67daf65dfb33c/微信图片_20240716153705.jpg with resolution 4032x3024 --> 512x384
 - adding /tmp/gradio/763be724fdba48f04a5dde5b8ec28f16e92b53ec/微信图片_20240716153712.jpg with resolution 4032x3024 --> 512x384
 - adding /tmp/gradio/d60a6d85853c4fde581524831ea275a7a5595327/微信图片_20240716153718.jpg with resolution 4032x3024 --> 512x384
 - adding /tmp/gradio/406e34151307a6a7067740dfc9e25c30b7c8aab7/微信图片_20240716153723.jpg with resolution 4032x3024 --> 512x384
 - adding /tmp/gradio/0343ca416b22a955fe9ae461084df6119ae31a52/微信图片_20240716153731.jpg with resolution 4032x3024 --> 512x384
 - adding /tmp/gradio/4eab94759a2093ac8c2c1df959a1777f66685be7/微信图片_20240716153736.jpg with resolution 4032x3024 --> 512x384
 (Found 10 images)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 90/90 [00:18<00:00,  4.91it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 16.63it/s]
init focals = [378.66293 329.46643 374.04337 379.07648 371.7553  379.46152 380.6603
 384.3954  526.5664  385.89526]
Traceback (most recent call last):
  File "/home/xzr/anaconda3/envs/mast3r/lib/python3.11/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xzr/anaconda3/envs/mast3r/lib/python3.11/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xzr/anaconda3/envs/mast3r/lib/python3.11/site-packages/gradio/blocks.py", line 1897, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xzr/anaconda3/envs/mast3r/lib/python3.11/site-packages/gradio/blocks.py", line 1483, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xzr/anaconda3/envs/mast3r/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xzr/anaconda3/envs/mast3r/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/xzr/anaconda3/envs/mast3r/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xzr/anaconda3/envs/mast3r/lib/python3.11/site-packages/gradio/utils.py", line 816, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "demo.py", line 145, in get_reconstructed_scene
    scene = sparse_global_alignment(filelist, pairs, os.path.join(outdir, 'cache'),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xzr/reconstruction/mast3r/mast3r/cloud_opt/sparse_ga.py", line 150, in sparse_global_alignment
    imgs, res_coarse, res_fine = sparse_scene_optimizer(
                                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xzr/reconstruction/mast3r/mast3r/cloud_opt/sparse_ga.py", line 315, in sparse_scene_optimizer
    subsamp_preds_21[imk][im2k] = (pred[idxs], conf[idxs])  # anchors subsample
                                   ~~~~^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [15,0,0], thread: [0,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [15,0,0], thread: [1,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [15,0,0], thread: [2,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [15,0,0], thread: [33,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [15,0,0], thread: [34,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [15,0,0], thread: [35,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [40,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [41,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [42,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [43,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [44,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [45,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [79,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [80,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [81,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [82,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [83,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [84,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [124,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [125,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [126,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [127,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [32,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [33,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [34,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [35,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [36,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [37,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [38,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [39,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [40,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [41,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [42,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [43,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [44,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [45,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [46,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [47,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [48,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [49,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [50,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [51,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [52,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [53,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [54,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [55,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [56,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [57,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [58,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [59,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [60,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [61,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [62,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905969073/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [12,0,0], thread: [63,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.

**Comment by yocabon** [comment]
Hi,
Could you give me more details ?
Does it crash right away (with an empty tmp_dir) or does it crash after a few reconstructions (could be wrong data in the cache file created by the sparse_ga, possible if there are name collisions).

**Comment by yocabon** [comment]
Hi, sorry about that, could you update the code and try again ?

**Comment by Xu-Zirui** [comment]
That's work!!! Thanks!
