### ISSUE TITLE
Failure on assert (core_depth > 0).all()

### ISSUE THREAD

**Issue by hturki** [naver/mast3r#19]
I'm not sure if this is related to https://github.com/naver/mast3r/issues/15, but running sparse GA (on 3 images the garden scene of mipnerf 360 in case that helps reproducibility) throws the following exception:

```
... loading model from /data/hturki/mast3r/checkpoints/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth
instantiating : AsymmetricMASt3R(enc_depth=24, dec_depth=12, enc_embed_dim=1024, dec_embed_dim=768, enc_num_heads=16, dec_num_heads=12, pos_embed='RoPE100',img_size=(512, 512), head_type='catmlp+dpt', output_mode='pts3d+desc24', depth_mode=('exp', -inf, inf), conf_mode=('exp', 1, inf), patch_embed_cls='PatchEmbedDust3R', two_confs=True, desc_conf_mode=('exp', 0, inf), landscape_only=False)
<All keys matched successfully>
>> Loading a list of 3 images
 - adding data/mipnerf360/garden/images/DSC07956.JPG with resolution 5187x3361 --> 512x320
 - adding data/mipnerf360/garden/images/DSC08017.JPG with resolution 5187x3361 --> 512x320
 - adding data/mipnerf360/garden/images/DSC08079.JPG with resolution 5187x3361 --> 512x320
 (Found 3 images)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 31575.69it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 46.42it/s]
init focals = [341.22675 366.47287 352.85052]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:04<00:00, 124.25it/s, lr=0.0000, loss=0.164]
>> final loss = 0.16400130093097687
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:05<00:00, 86.96it/s, lr=0.0000, loss=0.498]
>> final loss = 0.4979879856109619
Final focals = [375.3088  370.26553 369.79773]
Traceback (most recent call last):
  File "/home/hturki/miniconda3/envs/pixelnerf-nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/data/hturki/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/data/hturki/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/data/hturki/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/data/hturki/nerfstudio/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/data/hturki/nerfstudio/nerfstudio/engine/trainer.py", line 156, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/data/hturki/nerfstudio/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/data/hturki/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 259, in __init__
    self.datamanager: DataManager = config.datamanager.setup(
  File "/data/hturki/nerfstudio/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/data/hturki/nerfstudio/nerfstudio/data/datamanagers/full_images_datamanager.py", line 121, in __init__
    self.train_dataparser_outputs: DataparserOutputs = self.dataparser.get_dataparser_outputs(split="train")
  File "/data/hturki/generfstudio/generfstudio/data/dataparsers/depth_providing_dataparser.py", line 68, in get_dataparser_outputs
    pts3d, depthmaps, confs = scene.get_dense_pts3d(subsample=1)
  File "/data/hturki/mast3r/mast3r/cloud_opt/sparse_ga.py", line 82, in get_dense_pts3d
    idxs, offsets = anchor_depth_offsets(canon2, {i: (pixels, None)}, subsample=subsample)
  File "/data/hturki/mast3r/mast3r/cloud_opt/sparse_ga.py", line 866, in anchor_depth_offsets
    assert (core_depth > 0).all()
```

For what its worth, running dust3r's global_aligner method with the mast3r checkpoint seems to work reasonably well:

<img width="1481" alt="image" src="https://github.com/user-attachments/assets/35be34a1-64c8-4938-8fc8-46de5829fb0b">

**Comment by yocabon** [comment]
Hi,
I managed to run these 3 images with the sparse_ga without errors.
I think in:
```
File "/data/hturki/generfstudio/generfstudio/data/dataparsers/depth_providing_dataparser.py", line 68, in get_dataparser_outputs
    pts3d, depthmaps, confs = scene.get_dense_pts3d(subsample=1)
```
subsample=1 might be mismatched with the subsample=8 inside of sparse_global_alignment.

**Comment by hturki** [comment]
Thanks! Setting subsample=8 did the trick.
