### ISSUE TITLE
mast3r_sfm asmk issue

### ISSUE THREAD

**Issue by kevinhuangxf** [naver/mast3r#60]
HI. Thanks for the great work on mast3r_sfm. I want to try the demo but I got this error:

`Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead
Traceback (most recent call last):
  File "/workspace/code/mast3r_sfm/demo.py", line 13, in <module>
    from mast3r.demo import get_args_parser, main_demo
  File "/workspace/code/mast3r_sfm/mast3r/demo.py", line 23, in <module>
    from mast3r.retrieval.processor import Retriever
  File "/workspace/code/mast3r_sfm/mast3r/retrieval/processor.py", line 32, in <module>
    from asmk import asmk_method  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'asmk_method' from 'asmk' (unknown location)`

I've already installed faiss and asmk.

May I get any hint on how to solve this problem

Thx so much

**Comment by prajwalchidananda** [comment]
Try this
```
WORKDIR /mast3r/
RUN pip install pyaml faiss-gpu
RUN pip install cython
RUN git clone https://github.com/jenicek/asmk
WORKDIR /mast3r/asmk/cython/
RUN cythonize *.pyx
WORKDIR /mast3r/asmk/
RUN pip install .
```

**Comment by Jaykumaran** [comment]
```
pip install faiss-cpu
pip install cython
git clone https://github.com/jenicek/asmk
cd /mast3r/asmk/cython/
cythonize *.pyx
cd  /mast3r/asmk/
pip install .

```
