### ISSUE TITLE
AttributeError: module 'roma' has no attribute 'unitquat_to_rotmat'

### ISSUE THREAD

**Issue by nfyfamr** [naver/mast3r#75]
Thanks for sharing this great work! I got an error when trying mast3r-sfm branch. Do you have any idea for this? Thanks in advance!

init focals = [393.2743  376.9621  385.34326 402.16824 343.4522 ]
  0%|                                                                                                                                                                     | 0/300 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/ws/run_mast3r_sfm.py", line 518, in <module>
    run_mast3r_sfm(sfm_dir, database_path, [str(images_dir / im) for im in images_list])
  File "/ws/run_mast3r_sfm.py", line 427, in run_mast3r_sfm
    scene = get_reconstructed_scene(sfm_dir, model, retrieval_model, device, image_size,
  File "/ws/run_mast3r_sfm.py", line 499, in get_reconstructed_scene
    scene = sparse_global_alignment(filelist, pairs, cache_dir,
  File "/ws/mast3r/mast3r/cloud_opt/sparse_ga.py", line 189, in sparse_global_alignment
    imgs, res_coarse, res_fine = sparse_scene_optimizer(
  File "/ws/mast3r/mast3r/cloud_opt/sparse_ga.py", line 478, in sparse_scene_optimizer
    res_coarse = optimize_loop(loss_3d, lr_base=lr1, niter=niter1, pix_loss=loss1)
  File "/ws/mast3r/mast3r/cloud_opt/sparse_ga.py", line 439, in optimize_loop
    K, (w2cam, cam2w), depthmaps = make_K_cam_depth(log_focals, pps, trans, quats, log_sizes, core_depth)
  File "/ws/mast3r/mast3r/cloud_opt/sparse_ga.py", line 289, in make_K_cam_depth
    rel_cam2cam[:, :3, :3] = roma.unitquat_to_rotmat(F.normalize(torch.stack(quats), dim=1))
AttributeError: module 'roma' has no attribute 'unitquat_to_rotmat'

**Comment by nfyfamr** [comment]
Never mind, it was because python module confliction. Since I had already installed another roma (https://github.com/Parskatt/RoMa), the requirement.txt skip to install roma (https://naver.github.io/roma/).
